-- MySQL Script generated by MySQL Workbench
-- Sat Mar  5 17:22:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet_jakarta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projet_jakarta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet_jakarta` DEFAULT CHARACTER SET utf8 ;
USE `projet_jakarta` ;

-- -----------------------------------------------------
-- Table `projet_jakarta`.`Parcours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_jakarta`.`Parcours` (
  `idParcours` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParcours`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_jakarta`.`Formateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_jakarta`.`Formateur` (
  `idFormateur` INT NOT NULL AUTO_INCREMENT,
  `Questions_idQuestions` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `Université` VARCHAR(45) NOT NULL,
  `Parcours_idParcours` INT NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFormateur`),
  INDEX `fk_Formateur_Questions1_idx` (`Questions_idQuestions` ASC) VISIBLE,
  INDEX `fk_Formateur_Parcours1_idx` (`Parcours_idParcours` ASC) VISIBLE,
  CONSTRAINT `fk_Formateur_Questions1`
    FOREIGN KEY (`Questions_idQuestions`)
    REFERENCES `projet_jakarta`.`Questions` (`idQuestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formateur_Parcours1`
    FOREIGN KEY (`Parcours_idParcours`)
    REFERENCES `projet_jakarta`.`Parcours` (`idParcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_jakarta`.`Graphe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_jakarta`.`Graphe` (
  `idGraphe` INT NOT NULL,
  `Formateur_idFormateur` INT NOT NULL,
  PRIMARY KEY (`idGraphe`),
  INDEX `fk_Graphe_Formateur1_idx` (`Formateur_idFormateur` ASC) VISIBLE,
  CONSTRAINT `fk_Graphe_Formateur1`
    FOREIGN KEY (`Formateur_idFormateur`)
    REFERENCES `projet_jakarta`.`Formateur` (`idFormateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_jakarta`.`Compétences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_jakarta`.`Compétences` (
  `idCompétences` INT NOT NULL AUTO_INCREMENT,
  `Graphe_idGraphe` INT NOT NULL,
  PRIMARY KEY (`idCompétences`, `Graphe_idGraphe`),
  INDEX `fk_Compétences_Graphe1_idx` (`Graphe_idGraphe` ASC) VISIBLE,
  CONSTRAINT `fk_Compétences_Graphe1`
    FOREIGN KEY (`Graphe_idGraphe`)
    REFERENCES `projet_jakarta`.`Graphe` (`idGraphe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_jakarta`.`Questionnaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_jakarta`.`Questionnaire` (
  `idQuestionnaire` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idQuestionnaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_jakarta`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_jakarta`.`Questions` (
  `idQuestions` INT NOT NULL AUTO_INCREMENT,
  `Compétences_idCompétences` INT NOT NULL,
  `forme` VARCHAR(45) NOT NULL,
  `Questionnaire_idQuestionnaire` INT NOT NULL,
  PRIMARY KEY (`idQuestions`, `Questionnaire_idQuestionnaire`),
  INDEX `fk_Questions_Compétences_idx` (`Compétences_idCompétences` ASC) VISIBLE,
  INDEX `fk_Questions_Questionnaire1_idx` (`Questionnaire_idQuestionnaire` ASC) VISIBLE,
  CONSTRAINT `fk_Questions_Compétences`
    FOREIGN KEY (`Compétences_idCompétences`)
    REFERENCES `projet_jakarta`.`Compétences` (`idCompétences`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questions_Questionnaire1`
    FOREIGN KEY (`Questionnaire_idQuestionnaire`)
    REFERENCES `projet_jakarta`.`Questionnaire` (`idQuestionnaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_jakarta`.`Réponses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_jakarta`.`Réponses` (
  `idRéponses` INT NOT NULL AUTO_INCREMENT,
  `Points` INT NOT NULL,
  `Questions_idQuestions` INT NOT NULL,
  PRIMARY KEY (`idRéponses`, `Questions_idQuestions`),
  INDEX `fk_Réponses_Questions1_idx` (`Questions_idQuestions` ASC) VISIBLE,
  CONSTRAINT `fk_Réponses_Questions1`
    FOREIGN KEY (`Questions_idQuestions`)
    REFERENCES `projet_jakarta`.`Questions` (`idQuestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_jakarta`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_jakarta`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `formation` VARCHAR(45) NOT NULL,
  `Université` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `Graphe_idGraphe` INT NOT NULL,
  `Parcours_idParcours` INT NOT NULL,
  PRIMARY KEY (`idUtilisateur`, `Parcours_idParcours`),
  INDEX `fk_Utilisateur_Graphe1_idx` (`Graphe_idGraphe` ASC) VISIBLE,
  INDEX `fk_Utilisateur_Parcours1_idx` (`Parcours_idParcours` ASC) VISIBLE,
  CONSTRAINT `fk_Utilisateur_Graphe1`
    FOREIGN KEY (`Graphe_idGraphe`)
    REFERENCES `projet_jakarta`.`Graphe` (`idGraphe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_Parcours1`
    FOREIGN KEY (`Parcours_idParcours`)
    REFERENCES `projet_jakarta`.`Parcours` (`idParcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_jakarta`.`Formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_jakarta`.`Formation` (
  `idFormation` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `Compétences_idCompétences` INT NOT NULL,
  `Parcours_idParcours` INT NOT NULL,
  PRIMARY KEY (`idFormation`, `Compétences_idCompétences`, `Parcours_idParcours`),
  INDEX `fk_Formation_Compétences1_idx` (`Compétences_idCompétences` ASC) VISIBLE,
  INDEX `fk_Formation_Parcours1_idx` (`Parcours_idParcours` ASC) VISIBLE,
  CONSTRAINT `fk_Formation_Compétences1`
    FOREIGN KEY (`Compétences_idCompétences`)
    REFERENCES `projet_jakarta`.`Compétences` (`idCompétences`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formation_Parcours1`
    FOREIGN KEY (`Parcours_idParcours`)
    REFERENCES `projet_jakarta`.`Parcours` (`idParcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_jakarta`.`Graphe_has_Graphe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_jakarta`.`Graphe_has_Graphe` (
  `Graphe_idGraphe` INT NOT NULL,
  `Graphe_idGraphe1` INT NOT NULL,
  PRIMARY KEY (`Graphe_idGraphe`, `Graphe_idGraphe1`),
  INDEX `fk_Graphe_has_Graphe_Graphe2_idx` (`Graphe_idGraphe1` ASC) VISIBLE,
  INDEX `fk_Graphe_has_Graphe_Graphe1_idx` (`Graphe_idGraphe` ASC) VISIBLE,
  CONSTRAINT `fk_Graphe_has_Graphe_Graphe1`
    FOREIGN KEY (`Graphe_idGraphe`)
    REFERENCES `projet_jakarta`.`Graphe` (`idGraphe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Graphe_has_Graphe_Graphe2`
    FOREIGN KEY (`Graphe_idGraphe1`)
    REFERENCES `projet_jakarta`.`Graphe` (`idGraphe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_jakarta`.`Utilisateur_has_Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_jakarta`.`Utilisateur_has_Questions` (
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `Questions_idQuestions` INT NOT NULL,
  PRIMARY KEY (`Utilisateur_idUtilisateur`, `Questions_idQuestions`),
  INDEX `fk_Utilisateur_has_Questions_Questions1_idx` (`Questions_idQuestions` ASC) VISIBLE,
  INDEX `fk_Utilisateur_has_Questions_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Utilisateur_has_Questions_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `projet_jakarta`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Questions_Questions1`
    FOREIGN KEY (`Questions_idQuestions`)
    REFERENCES `projet_jakarta`.`Questions` (`idQuestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_jakarta`.`Utilisateur_has_Réponses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_jakarta`.`Utilisateur_has_Réponses` (
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `Réponses_idRéponses` INT NOT NULL,
  PRIMARY KEY (`Utilisateur_idUtilisateur`, `Réponses_idRéponses`),
  INDEX `fk_Utilisateur_has_Réponses_Réponses1_idx` (`Réponses_idRéponses` ASC) VISIBLE,
  INDEX `fk_Utilisateur_has_Réponses_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Utilisateur_has_Réponses_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `projet_jakarta`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Réponses_Réponses1`
    FOREIGN KEY (`Réponses_idRéponses`)
    REFERENCES `projet_jakarta`.`Réponses` (`idRéponses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
